version: '3.8'

services:
  service-a:
    build: ./servicoA
    container_name: ms_users
    ports:
      - "3000:3000"
    networks:
      - microservices-net

  service-b:
    build: ./servicoB
    container_name: ms_display
    ports:
      - "5000:5000"
    environment:
      - SERVICE_A_URL=http://service-a:3000/api/users
    depends_on:
      - service-a
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge